branch-defaults:
  default:
    environment: null
    group_suffix: null
  override-init:
    environment: sample-app-vb-localhost
    group_suffix: null
global:
  application_name: sample-app-vb
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
